# Generated by Django 6.0.3 on 2026-05-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review_unique_together_and_initial_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='active', max_length=10),
        ),
    ]
