# Generated by Django 6.0.3 on 2026-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_improvements_job_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='is_remote',
            field=models.BooleanField(default=True),
        ),
    ]
