from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("listings/", views.listing_list, name="listing_list"),
    path("listings/create/", views.listing_create, name="listing_create"),
    path("listings/<int:pk>/", views.listing_detail, name="listing_detail"),
    path("listings/<int:pk>/edit/", views.listing_edit, name="listing_edit"),
    path("listings/<int:pk>/bid/", views.place_bid, name="place_bid"),
    path("bids/<int:pk>/accept/", views.bid_accept, name="bid_accept"),
    path("bids/<int:pk>/reject/", views.bid_reject, name="bid_reject"),
    path("bids/<int:pk>/edit/", views.bid_edit, name="bid_edit"),
    path("bids/<int:pk>/delete/", views.bid_delete, name="bid_delete"),
    path("contracts/", views.contracts, name="contracts"),
    path("contracts/<int:pk>/", views.contract_detail, name="contract_detail"),
    path("contracts/<int:pk>/complete/", views.contract_complete, name="contract_complete"),
    path("contracts/<int:pk>/accept/", views.contract_accept, name="contract_accept"),
    path("contracts/<int:pk>/reject/", views.contract_reject, name="contract_reject"),
    path("contracts/<int:pk>/message/", views.contract_message_create, name="contract_message_create"),
    path("contracts/<int:contract_pk>/review/", views.review_create, name="review_create"),
    path("jobs/", views.job_request_list, name="job_request_list"),
    path("jobs/create/", views.job_request_create, name="job_request_create"),
    path("jobs/<int:pk>/", views.job_request_detail, name="job_request_detail"),
    path("jobs/<int:pk>/bid/", views.job_bid_create, name="job_bid_create"),
    path("job-bids/<int:pk>/accept/", views.job_bid_accept, name="job_bid_accept"),
    path("job-bids/<int:pk>/reject/", views.job_bid_reject, name="job_bid_reject"),
    path("notifications/", views.notifications_list, name="notifications_list"),
    path("notifications/mark-read/", views.notifications_mark_read, name="notifications_mark_read"),
    path("accounts/register/", views.register, name="register"),
    path("accounts/kyc-verify/", views.kyc_self_verify, name="kyc_self_verify"),
    path("profiles/<int:user_pk>/", views.profile_detail, name="profile_detail"),
]
